site_name: MyLorum
site_url: https://www.self.learn/
nav:
  - Home: index.md
  - About: about.md
theme: 
  name: material


features:
  - header.autohide
  # - navigation.instant
  # - navigation.expand
  # - navigation.sections
  - navigation.tracking
  # - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  # - navigation.indexes
  - search.highlight
  - search.share
  - search.suggest
  # - toc.integrate
  - content.code.annotate

palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode